DROP procedure [dbo].[SP_N_COTIZACION_INDIRECTA_DETALLES]
GO


CREATE procedure [dbo].[SP_N_COTIZACION_INDIRECTA_DETALLES]
	@cantidad bigint =null
	,@COTIZACION_INDIRECTA_ITEMS_id bigint  =null
	,@COTIZACION_SOLICITUD_COTIZACIONES_id bigint =null
	,@id bigint OUTPUT
as
begin
	INSERT INTO COTIZACION_INDIRECTA_DETALLES (
		cantidad
		,COTIZACION_INDIRECTA_ITEMS_id
		,COTIZACION_SOLICITUD_COTIZACIONES_id)
	VALUES (
		@cantidad
		,@COTIZACION_INDIRECTA_ITEMS_id
		,@COTIZACION_SOLICITUD_COTIZACIONES_id)
	select @id = SCOPE_IDENTITY()
	select @id
end	
GO