create table PuertosRelacion
(agente varchar (100),
puertoOrigen varchar (100),
puertoDestino varchar (100),
carga varchar (100),
armadorNaviera varchar (100)
)

go

Insert into PuertosRelacion values ('ADDICON','SIHANOUVILLE','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('AGC NEWTRAL','BILBAO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('AGC NEWTRAL','BILBAO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('AGC NEWTRAL','VALENCIA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('AGC NEWTRAL','BILBAO','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('AGC NEWTRAL','VALENCIA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('AGC NEWTRAL','BARCELONA','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('AIMAR SALVADOR','ACAJUTLA','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('AIMAR SALVADOR','ACAJUTLA','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('ALLTRANS INT CO','ALEXANDRIA','ARICA','FCL','MAERSK')
Insert into PuertosRelacion values ('ALLTRANS INT CO','ALEXANDRIA','ARICA','FCL','MAERSK')
Insert into PuertosRelacion values ('AUSTROMAR','HAMBURGO','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('BCR AUSTRALIA','FREMANTLE','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('COLGRUPAJES LTD','BUENAVENTURA','SAN ANTONIO','FCL','COSCO GROUP')
Insert into PuertosRelacion values ('COLGRUPAJES S.A','CARTAGENA','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CONTACT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CONTACT SPO','PECEM','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CONTACT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CONTACT STS','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CONTEMAR-COMP','LEIXOES','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('CRAFT CHILE','SANTOS','SAN ANTONIO','FCL','CRAFT')
Insert into PuertosRelacion values ('CRAFT CHILE','BALBOA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT CHILE','BILBAO','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('CRAFT CHILE','BUSAN','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('CRAFT CHILE','VADO LIGURE','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT CHILE','COLON','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('CRAFT SPO','RIO GRANDE','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','ITAGUAI','SAN VICENTE','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SALVADOR','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','ITAGUAI','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SALVADOR','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SALVADOR','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','RIO GRANDE','IQUIQUE','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','ANTOFAGASTA','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','ANTOFAGASTA','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','VITORIA','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','ITAGUAI','IQUIQUE','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','ITAGUAI','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SAO FRANCISCO','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SAO FRANCISCO','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SALVADOR','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT SPO','SANTOS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SAO FRANCISCO','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','IQUIQUE','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','ITAGUAI','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','ANTOFAGASTA','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','IQUIQUE','FCL','HAMBURG')
Insert into PuertosRelacion values ('CRAFT STS','SANTOS','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','OAKLAND','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','SAN VICENTE','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','OAKLAND','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','PORTLAND','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','PORTLAND','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','IQUIQUE','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','OAKLAND','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','LOS ANGELES','VALPARAISO','FCL','NYK')
Insert into PuertosRelacion values ('DGX','HOUSTON','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('GLOBELINK INDIA','CHENNAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','PIPAVAV','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDIA','KOLKATA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','KOLKATA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','PIPAVAV','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDIA','JNPT','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','MUNDRA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','NHAVA SHEVA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','NHAVA SHEVA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','KOLKATA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','PIPAVAV','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDIA','JNPT','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','KOLKATA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','MUNDRA','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK INDIA','PIPAVAV','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDIA','NHAVA SHEVA','ARICA','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('GLOBELINK INDON','JAKARTA','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('GLOBELINK INDON','ROTTERDAM','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDON','JAKARTA','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK INDON','JAKARTA','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLOBELINK KOREA','BUSAN','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('GLOBELINK KOREA','BUSAN','SAN VICENTE','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('GLOBELINK KOREA','BUSAN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK KOREA','BUSAN','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('GLOBELINK PAKIS','KARACHI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK PAKIS','KARACHI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('GLOBELINK SHANG','YANTIAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('GLOBELINK SHANG','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('GLOBELINK SHENZ','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('GLOBELINK SHENZ','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','ISTANBUL','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','AMBARLI','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','IZMIR','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','ISTANBUL','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','ISTANBUL','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','AMBARLI','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','AMBARLI','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','ISTANBUL','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('GLOBELINK UNIMA','AMBARLI','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('GLS INTERFREIGH','LAEM CHABANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLS INTERFREIGH','LAEM CHABANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLS INTERFREIGH','LAEM CHABANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLS INTERFREIGH','LAEM CHABANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GLS INTERFREIGH','LAEM CHABANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('GRUPOLIS','LEIXOES','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','PUERTO ANGAMOS','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','IQUIQUE','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','IQUIQUE','FCL','KAWASAKY')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MOL')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MOL')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','KAWASAKY')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','ARICA','FCL','CSAV')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','IQUIQUE','FCL','KAWASAKY')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('INTERCOM','MANZANILLO - MX','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('LOGFRET','VALENCIA','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('LOGFRET','VALENCIA','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('MARVEL FREIGHT','CHITTAGONG','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('MARVEL FREIGHT','CHITTAGONG','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('MARVEL FREIGHT','CHITTAGONG','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('MARVEL FREIGHT','CHITTAGONG','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('MCL LOJISTIK','ISTANBUL','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('MCL LOJISTIK','GEMLIK','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('MCL LOJISTIK','HAYDARPASA','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('MERCURY','HAIPHONG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('MERCURY','HOCHIMINH CITY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('MERCURY','HAIPHONG','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('MPG LOGISTICS','BILBAO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('MPG TRANSITOS','VALENCIA','VALPARAISO','FCL','CMA CGM')
Insert into PuertosRelacion values ('MSI','LAEM CHABANG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('NISSIN CORPORAT','KOBE','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('NISSIN CORPORAT','YOKOHAMA','BUENAVENTURA','FCL','HAMBURG')
Insert into PuertosRelacion values ('NISSIN CORPORAT','YOKOHAMA','BUENAVENTURA','FCL','HAMBURG')
Insert into PuertosRelacion values ('NORDICON','AARHUS','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('ORIENTAL HONG K','RONGQI','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('ORIENTAL NINGBO','NINGBO','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('ORIENTAL SHANG','SHANGHAI','LIRQUEN','FCL','MITSUI')
Insert into PuertosRelacion values ('ORIENTAL TAIWAN','KEELUNG','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('ORIENTAL TAIWAN','KEELUNG','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('ORIENTAL TAIWAN','KAOHSIUNG','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('ORIENTAL TAIWAN','KAOHSIUNG','SAN VICENTE','FCL','MAERSK')
Insert into PuertosRelacion values ('ORIENTAL TAIWAN','KEELUNG','VALPARAISO','FCL','MITSUI')
Insert into PuertosRelacion values ('RUSH','CALLAO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('RUSH','CALLAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('RUSH','CALLAO','VALPARAISO','FCL','APL')
Insert into PuertosRelacion values ('RUSH','CALLAO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('RUSH','CALLAO','SAN ANTONIO','FCL','COSCO GROUP')
Insert into PuertosRelacion values ('RUSH','CALLAO','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SARAYU MARITIME','GTI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SEACON','ANTWERP','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SEACON','ROTTERDAM','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SEACON','ANTWERP','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SEACON','LE HAVRE','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SEACON','ANTWERP','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SEINO LOGIX CO.','YOKOHAMA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SEINO LOGIX CO.','YOKOHAMA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SEINO LOGIX CO.','YOKOHAMA','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XINGANG','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XINGANG','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','FUZHOU','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XINGANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','HUANGPU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XINGANG','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','WUHAN','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','XIAMEN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS FUJIAN','RONGQI','BUENAVENTURA','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS HONGKO','HONG KONG','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS HONGKO','HONG KONG','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS HONGKO','HONG KONG','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS HONGKO','HONG KONG','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','CALLAO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS NINGBO','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','SAN ANTONIO','FCL','CMA CGM')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','LIANYUGANG','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS QINGDA','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHA','SHANGHAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','XIAOLAN','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','HONG KONG','SAN ANTONIO','FCL','WAN HAI LINES')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','WUHAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','SAN VICENTE','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','XINGANG','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','WUHAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NINGBO','BUENAVENTURA','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NINGBO','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','ZHANGJIAGANG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NINGBO','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','TIANJIN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','XINGANG','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','TIANJIN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','XINGANG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','TIANJIN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NANJING','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','YANTIAN','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','SAN VICENTE','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','BUSAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','NANJING','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','DALIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','QINGDAO','SAN VICENTE','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','QINGDAO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','BUENAVENTURA','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHANGH','SHANGHAI','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','XIAOLAN','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHANTOU','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHEKOU','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','LANSHI','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHUNDE','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','GUANGZHOU','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','XIAOLAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','SAN ANTONIO','FCL','PIL')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHUNDE','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHUNDE','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','SAN ANTONIO','FCL','WAN HAI LINES')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','XIAOLAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHANTOU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DACHANBAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHEKOU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHANTOU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHEKOU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','RONGQI','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HAPAG')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHUNDE','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','RONGQI','BUENAVENTURA','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','SHEKOU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','DA CHAN BAY','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','JIANGMEN','ANTOFAGASTA','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','WUHAN','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','YANTIAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','HUANGPU','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS SHENZH','XIAOLAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KEELUNG','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KEELUNG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KEELUNG','VALPARAISO','FCL','CCNI')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KEELUNG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KAOHSIUNG','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','TAOYUAN','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KAOHSIUNG','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('SYNTRANS TAIWAN','KEELUNG','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('TRAFFIC TECH','MONTREAL','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','IQUIQUE','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MANZANILLO - MX','PUERTO ANGAMOS','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('TRAFFIC TECH','HOUSTON','SAN ANTONIO','FCL','MAERSK')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','IQUIQUE','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','CHARLESTON','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','IQUIQUE','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','IQUIQUE','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','PORT EVERGLADES','VALPARAISO','FCL','CSAV')
Insert into PuertosRelacion values ('TRAFFIC TECH','BALTIMORE','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','MIAMI','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NORFOLK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','SAN ANTONIO','FCL','EVERGREEN')
Insert into PuertosRelacion values ('TRAFFIC TECH','CHARLESTON','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('TRAFFIC TECH','PORT EVERGLADES','SAN ANTONIO','FCL','HAMBURG')
Insert into PuertosRelacion values ('TRAFFIC TECH','NEW YORK','BUENOS AIRES','FCL','CSAV')
Insert into PuertosRelacion values ('TRAFFIC TECH','HOUSTON','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('TRAFFIC TECH','HOUSTON','SAN ANTONIO','FCL','CCNI')
Insert into PuertosRelacion values ('TRANSCINCO TRAN','LEIXOES','SAN ANTONIO','FCL','CSAV')
Insert into PuertosRelacion values ('TRANSGLOBAL','TILBURY','ARICA','FCL','CSAV')
Insert into PuertosRelacion values ('TRANSGLOBAL','CALLAO','ARICA','FCL','CSAV')
Insert into PuertosRelacion values ('TRANSGLOBAL','TILBURY','ARICA','FCL','CSAV')
Insert into PuertosRelacion values ('TRANSGLOBAL','ALEXANDRIA','ARICA','FCL','MAERSK  LOGISTIC')
Insert into PuertosRelacion values ('TRANSGLOBAL','HAMBURGO','ANTOFAGASTA','FCL','HAMBURG')
Insert into PuertosRelacion values ('TRANSGLOBAL','TILBURY','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('TRANSGLOBAL','TILBURY','VALPARAISO','FCL','HAMBURG')
Insert into PuertosRelacion values ('TRANSGLOBAL','TILBURY','SAN ANTONIO','FCL','MEDITERRANEAN')
Insert into PuertosRelacion values ('TRANSMODE','PORT KELANG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('TRANSMODE','PORT KELANG','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('TRANSMODE','PORT KELANG','VALPARAISO','FCL','KAWASAKY')
Insert into PuertosRelacion values ('TUSCOR LLOYDS','GRANGEMOUTH','ARICA','FCL','HAPAG')
Insert into PuertosRelacion values ('WSL LINES LIMIT','NINGBO','VALPARAISO','FCL','HANJIN SHIPPING')
Insert into PuertosRelacion values ('WSL LINES LIMIT','SHEKOU','VALPARAISO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('WSL LINES LIMIT','XINGANG','CALLAO','FCL','CHINA SHIPPING')
Insert into PuertosRelacion values ('ZIEGLER SOUTH A','DURBAN','PUERTO ANGAMOS','FCL','MEDITERRANEAN')
go

/*
update PAPERLESS_NAVIERA set Descripcion = 'CCNI'  where Id = 1
go

insert into PAPERLESS_NAVIERA values('CHINA SHIPPING',1,getdate())
insert into PAPERLESS_NAVIERA values('CMA CGM',1,getdate())
insert into PAPERLESS_NAVIERA values('CSAV',1,getdate())
insert into PAPERLESS_NAVIERA values('EVERGREEN',1,getdate())
insert into PAPERLESS_NAVIERA values('HAMBURG',1,getdate())
insert into PAPERLESS_NAVIERA values('HAPAG LLOYD',1,getdate())
insert into PAPERLESS_NAVIERA values('KAWASAKY',1,getdate())
insert into PAPERLESS_NAVIERA values('MAERSK',1,getdate())
insert into PAPERLESS_NAVIERA values('MEDITERRANEAN',1,getdate())
insert into PAPERLESS_NAVIERA values('MOL',1,getdate())
insert into PAPERLESS_NAVIERA values('NYK',1,getdate())
insert into PAPERLESS_NAVIERA values('PIL',1,getdate())
insert into PAPERLESS_NAVIERA values('WAN HAI LINES',1,getdate())
insert into PAPERLESS_NAVIERA values('HANJIN SHIPPING',1,getdate())
insert into PAPERLESS_NAVIERA values('Hyundai',1,getdate())
insert into PAPERLESS_NAVIERA values('APL',1,getdate())
insert into PAPERLESS_NAVIERA values('COSCO',1,getdate())
go
*/
truncate table NAVIERA_PUERTO
go
--carga Puerto Destino
declare @descripcion varchar (100)
declare @IdNaviera varchar (100)
declare @CodigoPuerto varchar (100)
declare @existe varchar (100)

DECLARE CargaPuertosNavierasPuertoDestino CURSOR 
FOR 

select distinct pa.id as IdNaviera,p.codigo as CodigoPuerto from PAPERLESS_NAVIERA PA 
inner join PuertosRelacion PR on pa.Descripcion=PR.armadorNaviera
inner join Puertos P on p.nombre=pr.puertoDestino
OPEN CargaPuertosNavierasPuertoDestino

FETCH CargaPuertosNavierasPuertoDestino INTO @IdNaviera,@CodigoPuerto
WHILE (@@FETCH_STATUS = 0)
BEGIN	
-- Lectura de la siguiente fila de un cursor

FETCH CargaPuertosNavierasPuertoDestino INTO @IdNaviera,@CodigoPuerto
select @existe='0'
select @existe =(select count(*) from NAVIERA_PUERTO where idNaviera=@IdNaviera and puerto=@CodigoPuerto)

if (@existe=0)
begin
insert into NAVIERA_PUERTO values (@IdNaviera,@CodigoPuerto)
end

END -- Fin del bucle WHILE
CLOSE CargaPuertosNavierasPuertoDestino
DEALLOCATE CargaPuertosNavierasPuertoDestino
go

--Carga Puerto Origen
declare @descripcion varchar (100)
declare @IdNaviera varchar (100)
declare @CodigoPuerto varchar (100)
declare @existe varchar (100)

DECLARE CargaPuertosNavierasPuertoOrigen CURSOR 
FOR 

select distinct pa.id as IdNaviera,p.codigo as CodigoPuerto from PAPERLESS_NAVIERA PA 
inner join PuertosRelacion PR on pa.Descripcion=PR.armadorNaviera
inner join Puertos P on p.nombre=pr.puertoOrigen
OPEN CargaPuertosNavierasPuertoOrigen

FETCH CargaPuertosNavierasPuertoOrigen INTO @IdNaviera,@CodigoPuerto
WHILE (@@FETCH_STATUS = 0)
BEGIN	
-- Lectura de la siguiente fila de un cursor


FETCH CargaPuertosNavierasPuertoOrigen INTO @IdNaviera,@CodigoPuerto
select @existe='0'
select @existe =(select count(*)from NAVIERA_PUERTO where idNaviera=@IdNaviera and puerto=@CodigoPuerto)

if (@existe=0)
begin
insert into NAVIERA_PUERTO values (@IdNaviera,@CodigoPuerto)
end


END -- Fin del bucle WHILE
CLOSE CargaPuertosNavierasPuertoOrigen
DEALLOCATE CargaPuertosNavierasPuertoOrigen
go
