ALTER  PROCEDURE [DBO].[SP_L_PAPERLESS_CANTIDAD_ASIGNACIONES]
@USUARIO VARCHAR (20),
@DESDE DATETIME,
@HASTA DATETIME
AS  


IF YEAR(@DESDE) = 9999 SET @DESDE = NULL
IF YEAR(@HASTA) = 9999 SET @HASTA = NULL


DECLARE @SQL VARCHAR(4000)
SET @SQL = 'SELECT COUNT(*) CANT,USUARIOS.NOMBREUSUARIO '
SET @SQL += 'FROM PAPERLESS_ASIGNACION PA '
SET @SQL += 'INNER JOIN USUARIOS ON USUARIOS.ID = PA.'+@USUARIO+''

IF (@DESDE IS NOT NULL AND @DESDE <> '')    
    SET @SQL += ' WHERE CONVERT(VARCHAR(20),PA.FECHACREACION,112) >= ISNULL('''+CONVERT(NVARCHAR(20),@DESDE,112)+''',PA.FECHACREACION) '

IF (@HASTA IS NOT NULL AND @HASTA <> '')    
    SET @SQL += ' AND CONVERT(VARCHAR(20),PA.FECHACREACION,112) <= ISNULL('''+CONVERT(NVARCHAR(20),@HASTA,112)+''',PA.FECHACREACION) '

 SET @SQL += ' GROUP BY USUARIOS.NOMBREUSUARIO '

PRINT @SQL

EXECUTE(@SQL)