use SCCTEST
go

drop table COTIZACION_COMENTARIOS

CREATE TABLE [dbo].[COTIZACION_COMENTARIOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[fecha] [datetime] NULL,
	[EsHistorial] [bit] NULL,
	[Comentario] [varchar](500) NULL,
	[idUsuario] [bigint] NULL,
	[COTIZACION_SOLICITUD_COTIZACIONES_id] [bigint] NOT NULL,
	[CreateDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_DIRECTA_COMENTARIOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[fecha] [datetime] NULL,
	[EsHistorial] [bit] NULL,
	[Comentario] [varchar](500) NULL,
	[idUsuario] [bigint] NULL,
	[COTIZACION_DIRECTA_OPCIONES_id] [bigint] NOT NULL,
	[CreateDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_DIRECTA_CONCEPTOS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[ACTIVO] [bit] NULL,
	[CREATEDATE] [datetime] NULL,
 CONSTRAINT [PK_COTIZACION_DIRECTA_CONCEPTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[COTIZACION_DIRECTA_ESTADOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[activo] [bit] NULL,
	[createdate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_DIRECTA_ITEMS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](45) NULL,
	[descripcion] [varchar](100) NULL,
	[activo] [bit] NULL,
	[createdate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[numero] [varchar](45) NULL,
	[fechaValidezInicio] [datetime] NULL,
	[fechaValidezFin] [datetime] NULL,
	[Naviera] [bigint] NULL,
	[POD] [varchar](50) NULL,
	[POL] [varchar](50) NULL,
	[TiempoTransito] [varchar](50) NULL,
	[idUsuario] [bigint] NULL,
	[createDate] [datetime] NULL,
	[COTIZACION_SOLICITUD_COTIZACIONES_id] [bigint] NOT NULL,
	[COTIZACION_DIRECTA_ESTADOS_id] [bigint] NOT NULL,
 CONSTRAINT [PK__COTIZACI__3213E83F7BD05397] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[cantidad] [decimal](10, 6) NULL,
	[costo] [decimal](10, 6) NULL,
	[venta] [decimal](10, 6) NULL,
	[COTIZACION_MONEDAS_id] [bigint] NOT NULL,
	[COTIZACION_DIRECTA_ITEMS_id] [bigint] NOT NULL,
	[COTIZACION_DIRECTA_OPCIONES_id] [bigint] NOT NULL,
	[COTIZACION_DIRECTA_CONCEPTO_ID] [bigint] NULL,
	[CreateDate] [datetime] NULL,
 CONSTRAINT [PK__COTIZACI__3213E83F092A4EB5] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_PUERTOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[puerto] [varchar](10) NOT NULL,
	[cotizacion_directa_opciones_id] [bigint] NOT NULL,
	[tipo] [varchar](5) NOT NULL,
 CONSTRAINT [PK_COTIZACION_DIRECTA_OPCIONES_PUERTOS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


drop table Cotizacion_DetalleTarifa
go
drop table COTIZACION_MONEDAS
go

CREATE TABLE [dbo].[COTIZACION_MONEDAS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[codigo] [varchar](3) NULL,
	[nombre] [varchar](45) NULL,
	[activo] [bit] NULL,
	[createDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[producto] [varchar](20) NULL,
	[idUsuario] [bigint] NULL,
	[idCliente] [bigint] NULL,
	[idTarget] [bigint] NULL,
	[nombreCliente] [varchar](45) NULL,
	[fechaSolicitud] [datetime] NULL,
	[idIncoterms] [bigint] NOT NULL,
	[commodity] [varchar](60) NULL,
	[puertoEmbarque] [varchar](100) NULL,
	[POL] [varchar](10) NULL,
	[POD] [varchar](10) NULL,
	[navieraReferencia] [varchar](45) NULL,
	[tarifaReferencia] [varchar](45) NULL,
	[ObservacionesFijas] [varchar](500) NULL,
	[Observaciones] [varchar](500) NULL,
	[mercaderia] [varchar](45) NULL,
	[gastosLocales] [decimal](18, 0) NULL,
	[proveedorCarga] [varchar](45) NULL,
	[credito] [varchar](45) NULL,
	[fechaEstimadaEmbarque] [varchar](45) NULL,
	[conAgenciamento] [bit] NOT NULL,
	[createDate] [datetime] NOT NULL,
	[COTIZACION_TIPOS_TRANSBORDOS_id] [bigint] NULL,
	[COTIZACION_Directa_ESTADOS_id] [bigint] NOT NULL,
	[COTIZACION_TIPOS_id] [bigint] NOT NULL,
 CONSTRAINT [PK__COTIZACI__3213E83F69B1A35C] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


drop table Cotizacion_CotizacionDirecta_Opciones
drop table Cotizacion_Tarifas
drop table Cotizacion_Cotizaciones
go
drop table COTIZACION_TIPOS
go


CREATE TABLE [dbo].[COTIZACION_TIPOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](45) NULL,
	[createDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[COTIZACION_TIPOS_TRANSBORDOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](45) NOT NULL,
	[createDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[NAVIERA_PUERTO](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[idNaviera] [bigint] NOT NULL,
	[puerto] [varchar](10) NOT NULL,
 CONSTRAINT [PK_NAVIERA_PUERTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[Puertos](
	[codigo] [varchar](10) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[pais] [varchar](100) NOT NULL,
	[createDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Puertos_1] PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[COTIZACION_COMENTARIOS]  WITH CHECK ADD  CONSTRAINT [COTIZACION_COMENTARIOS_COTIZACION_SOLICITUD_COTIZACIONES] FOREIGN KEY([COTIZACION_SOLICITUD_COTIZACIONES_id])
REFERENCES [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_COMENTARIOS] CHECK CONSTRAINT [COTIZACION_COMENTARIOS_COTIZACION_SOLICITUD_COTIZACIONES]
GO

ALTER TABLE [dbo].[COTIZACION_COMENTARIOS] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_COMENTARIOS]  WITH CHECK ADD  CONSTRAINT [COTIZACION_DIRECTA_COMENTARIOS_COTIZACION_DIRECTA_OPCIONES] FOREIGN KEY([COTIZACION_DIRECTA_OPCIONES_id])
REFERENCES [dbo].[COTIZACION_DIRECTA_OPCIONES] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_COMENTARIOS] CHECK CONSTRAINT [COTIZACION_DIRECTA_COMENTARIOS_COTIZACION_DIRECTA_OPCIONES]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_COMENTARIOS] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO


ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_COTIZACION_SOLICITUD_COTIZACIONES] FOREIGN KEY([COTIZACION_SOLICITUD_COTIZACIONES_id])
REFERENCES [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES] CHECK CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_COTIZACION_SOLICITUD_COTIZACIONES]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_PAPERLESS_NAVIERA] FOREIGN KEY([Naviera])
REFERENCES [dbo].[PAPERLESS_NAVIERA] ([Id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES] CHECK CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_PAPERLESS_NAVIERA]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES] ADD  CONSTRAINT [DF__COTIZACIO__creat__7DB89C09]  DEFAULT (getdate()) FOR [createDate]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_ITEMS] FOREIGN KEY([COTIZACION_DIRECTA_ITEMS_id])
REFERENCES [dbo].[COTIZACION_DIRECTA_ITEMS] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES] CHECK CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_ITEMS]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_OPCIONES] FOREIGN KEY([COTIZACION_DIRECTA_OPCIONES_id])
REFERENCES [dbo].[COTIZACION_DIRECTA_OPCIONES] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES] CHECK CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_OPCIONES]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS] FOREIGN KEY([COTIZACION_MONEDAS_id])
REFERENCES [dbo].[COTIZACION_MONEDAS] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES] CHECK CONSTRAINT [COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_CONCEPTOS] FOREIGN KEY([COTIZACION_DIRECTA_CONCEPTO_ID])
REFERENCES [dbo].[COTIZACION_DIRECTA_CONCEPTOS] ([ID])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES] CHECK CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_CONCEPTOS]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_DETALLES] ADD  CONSTRAINT [DF__COTIZACIO__Creat__0B129727]  DEFAULT (getdate()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_PUERTOS]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_PUERTOS_COTIZACION_DIRECTA_OPCIONES_PUERTOS] FOREIGN KEY([puerto])
REFERENCES [dbo].[Puertos] ([codigo])
GO

ALTER TABLE [dbo].[COTIZACION_DIRECTA_OPCIONES_PUERTOS] CHECK CONSTRAINT [FK_COTIZACION_DIRECTA_OPCIONES_PUERTOS_COTIZACION_DIRECTA_OPCIONES_PUERTOS]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_SOLICITUD_COTIZACIONES_TIPOS] FOREIGN KEY([COTIZACION_TIPOS_id])
REFERENCES [dbo].[COTIZACION_TIPOS] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] CHECK CONSTRAINT [COTIZACION_SOLICITUD_COTIZACIONES_TIPOS]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES]  WITH CHECK ADD  CONSTRAINT [COTIZACION_SOLICITUD_COTIZACIONES_TIPOS_TRANSBORDOS] FOREIGN KEY([COTIZACION_TIPOS_TRANSBORDOS_id])
REFERENCES [dbo].[COTIZACION_TIPOS_TRANSBORDOS] ([id])
GO

--ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] CHECK CONSTRAINT [COTIZACION_SOLICITUD_COTIZACIONES_TIPOS_TRANSBORDOS]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_COTIZACION_DIRECTA_ESTADOS] FOREIGN KEY([COTIZACION_Directa_ESTADOS_id])
REFERENCES [dbo].[COTIZACION_DIRECTA_ESTADOS] ([id])
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] CHECK CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_COTIZACION_DIRECTA_ESTADOS]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_Puertos] FOREIGN KEY([POD])
REFERENCES [dbo].[Puertos] ([codigo])
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] CHECK CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_Puertos]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES]  WITH CHECK ADD  CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_Puertos1] FOREIGN KEY([POL])
REFERENCES [dbo].[Puertos] ([codigo])
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] CHECK CONSTRAINT [FK_COTIZACION_SOLICITUD_COTIZACIONES_Puertos1]
GO

ALTER TABLE [dbo].[COTIZACION_SOLICITUD_COTIZACIONES] ADD  CONSTRAINT [DF__COTIZACIO__creat__6B99EBCE]  DEFAULT (getdate()) FOR [createDate]
GO

ALTER TABLE [dbo].[COTIZACION_TIPOS] ADD  DEFAULT (getdate()) FOR [createDate]
GO

ALTER TABLE [dbo].[COTIZACION_TIPOS_TRANSBORDOS] ADD  DEFAULT (getdate()) FOR [createDate]
GO

ALTER TABLE [dbo].[NAVIERA_PUERTO]  WITH CHECK ADD  CONSTRAINT [FK_NAVIERA_PUERTO_NAVIERA_PUERTO] FOREIGN KEY([idNaviera])
REFERENCES [dbo].[PAPERLESS_NAVIERA] ([Id])
GO

ALTER TABLE [dbo].[NAVIERA_PUERTO] CHECK CONSTRAINT [FK_NAVIERA_PUERTO_NAVIERA_PUERTO]
GO

ALTER TABLE [dbo].[NAVIERA_PUERTO]  WITH CHECK ADD  CONSTRAINT [FK_NAVIERA_PUERTO_Puertos] FOREIGN KEY([puerto])
REFERENCES [dbo].[Puertos] ([codigo])
GO

ALTER TABLE [dbo].[NAVIERA_PUERTO] CHECK CONSTRAINT [FK_NAVIERA_PUERTO_Puertos]
GO


