ALTER TABLE
    dbo.COTIZACION_SOLICITUD_COTIZACIONES ADD COTIZACION_INDirecta_ESTADOS_id bigint;
ALTER TABLE
    dbo.COTIZACION_SOLICITUD_COTIZACIONES ADD idUsuarioPricing bigint;

ALTER TABLE
    dbo.COTIZACION_COMENTARIOS ADD IdEstadoAnterior bigint;

ALTER TABLE
    dbo.COTIZACION_COMENTARIOS ADD IdEstadoNuevo bigint;

ALTER TABLE
    dbo.COTIZACION_SOLICITUD_COTIZACIONES ALTER COLUMN COTIZACION_Directa_ESTADOS_id bigint NULL;
 
 
CREATE TABLE COTIZACION_INDIRECTA_ESTADOS (
	id BIGINT NOT NULL IDENTITY, 
	nombre VARCHAR(50), 
	activo BIT, 
	comentario varchar(500),
	createdate DATETIME, 
	PRIMARY KEY (id)
);

CREATE TABLE COTIZACION_INDIRECTA_DETALLES (
	id BIGINT NOT NULL IDENTITY,
	cantidad DECIMAL(10,6), 
	COTIZACION_INDIRECTA_ITEMS_id BIGINT NOT NULL,
	COTIZACION_SOLICITUD_COTIZACIONES_id BIGINT NOT NULL,	
	CreateDate DATETIME DEFAULT getdate(), 
	PRIMARY KEY (id)
);

CREATE TABLE COTIZACION_INDIRECTA_ITEMS (
	id BIGINT NOT NULL IDENTITY,
	nombre VARCHAR(45) , 
	descripcion VARCHAR(100) , 
	activo BIT, 
	createdate DATETIME, 
	PRIMARY KEY (id)
);


/*FOREING KEY  */

ALTER TABLE
    dbo.COTIZACION_SOLICITUD_COTIZACIONES ADD CONSTRAINT
    COTIZACION_SOLICITUD_COTIZACIONES_fk6 FOREIGN KEY (COTIZACION_INDirecta_ESTADOS_id) REFERENCES
    COTIZACION_INDIRECTA_ESTADOS (id);

ALTER TABLE
    dbo.COTIZACION_INDIRECTA_DETALLES ADD CONSTRAINT COTIZACION_INDIRECTA_DETALLES_fk1
    FOREIGN KEY (COTIZACION_SOLICITUD_COTIZACIONES_id) REFERENCES
    COTIZACION_SOLICITUD_COTIZACIONES (id);
    
ALTER TABLE
    COTIZACION_INDIRECTA_DETALLES ADD CONSTRAINT COTIZACION_INDIRECTA_DETALLES_fk2
    FOREIGN KEY (COTIZACION_INDIRECTA_ITEMS_id) REFERENCES COTIZACION_INDIRECTA_ITEMS    (id);
    
    
/* modulo de pricing */



CREATE TABLE COTIZACION_INDIRECTA_OPCIONES (
	id BIGINT NOT NULL IDENTITY, 
	numero VARCHAR(45),  
	fechaValidezInicio DATETIME, 
	fechaValidezFin DATETIME, 
	Naviera BIGINT,
	pickup VARCHAR(100),
	POD VARCHAR(50),  
	POL VARCHAR(50),  
	TiempoTransbordo VARCHAR(50),  
	idUsuario BIGINT, 
	agente VARCHAR(150),
	COTIZACION_TIPOS_TRANSBORDOS_id BIGINT,
	createDate DATETIME DEFAULT getdate(), 
	COTIZACION_SOLICITUD_COTIZACIONES_id BIGINT NOT NULL, 
	COTIZACION_INDIRECTA_ESTADOS_id BIGINT NOT NULL, 
	COTIZACION_INDIRECTA_TARIFAS_COPIADA_DE BIGINT,
	PRIMARY KEY (id),
	Observaciones varchar (500),
	ObservacionesFijas varchar (500),
);

CREATE TABLE COTIZACION_INDIRECTA_OPCIONES_DETALLES (
	id BIGINT NOT NULL IDENTITY, 
	cantidad DECIMAL(10,6), 
	costo DECIMAL(10,6), 
	venta DECIMAL(10,6),
	COTIZACION_MONEDAS_id BIGINT NOT NULL,
	COTIZACION_DIRECTA_ITEMS_id BIGINT NOT NULL, 
	COTIZACION_DIRECTA_OPCIONES_id BIGINT NOT NULL, 
	CreateDate DATETIME DEFAULT getdate(), 
	PRIMARY KEY (id), 
);
