
truncate table CALENDARIO_VISITA_INFORME_TRAFICOS
truncate table CALENDARIO_VISITA_INFORME_PRODUCTOS
truncate table CALENDARIO_VISITA_INFORME
truncate table CALENDARIO_VISITA_ASISTENTE
truncate table CALENDARIO_VISITA
truncate table LOG_EMAILS_CALENDARIO
truncate table CALENDARIO_VISITA_INFORME_COMENTARIO_USUARIO
truncate table CALENDARIO_VISITA_INFORME_COMENTARIO
truncate table VENTAS_LLAMADA_TELEFONICA
truncate table LOG_ACTIVIDAD_USUARIOS
truncate table Log
truncate table LOG_PERFORMANCE
truncate table PAPERLESS_ASIGNACION
truncate table PAPERLESS_LOG_FECHA_APERTURA_NAVIERAS
truncate table PAPERLESS_PROCESOS_REGISTRO_TIEMPOS
truncate table PAPERLESS_USUARIO1_EXCEPCIONES
truncate table PAPERLESS_USUARIO1_HOUSESBL
truncate table PAPERLESS_USUARIO1_HOUSESBL_INFO
truncate table PAPERLESS_USUARIO1_PASOS_ESTADO
truncate table PAPERLESS_USUARIO2_PASOS_ESTADO
truncate table DIRECCION_SLEAD_OBSERVACIONES
truncate table PAPERLESS_ASIGNACION_RECHAZO
go

drop table DIRECCION_META_GLOSA_PROD
drop table VENTAS_TIPO_TRAFICO_PUERTOS
drop table VENTAS_OPORTUNIDAD_TRAFICOS
drop table VENTAS_OPORTUNIDAD_PRODUCTOS
drop table VENTAS_GASTOS_LOCALES
drop table VENTAS_MAIL_CONTACTOS
drop table VENTAS_MAIL
drop table VENTAS_COTIZACION_EXFABRICA
drop table VENTAS_COTIZACION_CONDICIONES
drop table VENTAS_COTIZACION_FLETE
drop table CLIENTES_CONDICION_COMERCIAL_ESTADO
drop table CLIENTES_CONDICION_COMERCIAL_TIPO
drop table CLIENTES_CONTACTO_RELACIONADO
drop table CLIENTES_GASTOS_LOCAL
drop table CLIENTES_MASTER_PRODUCTOS
drop table CLIENTES_TARIFADO
drop table TARIFADO_FRECUENCIA
drop table TARIFADO_GLOSA_CONDICIONES
drop table TARIFADO_MEDIO
drop table TARIFADO_PUERTOS
drop table TARIFADO_SERVICIO_VIA
drop table TARIFADO_SERVICIOS
drop table TARIFADO_TIPOS_SERVICIO
drop table TARIFADO_UNIDADES
drop table VENTAS_COTIZACION_ENCABEZADO
drop table vENTAS_TIPOS_PRODUCTO_TRAFICO
drop table VENTAS_CONDICIONES_PAGO
go


Truncate table PAPERLESS_NAVE
go
truncate table PAPERLESS_NAVIERA
go