insert into paperless_puertos values ('AEDXB','DUBAI','UNITED ARABI EMIRATES',GetDate(),1)
insert into paperless_puertos values ('AEJEA','JEBEL ALI','UNITED ARABI EMIRATES',GetDate(),1)
insert into paperless_puertos values ('AEKLF','KHOR FAKKAN','UNITED ARABI EMIRATES',GetDate(),1)
insert into paperless_puertos values ('ANPHI','PHILIPSBURG','ST. MAARTEN',GetDate(),1)
insert into paperless_puertos values ('AOLAD','LUANDA','ANGOLA',GetDate(),1)
insert into paperless_puertos values ('ARBUE','BUENOS AIRES','ARGENTINA',GetDate(),1)
insert into paperless_puertos values ('AUADL','ADELAIDE','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUBNE','BRISBANE','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUBUY','BUNBURY','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUFRE','FREMANTLE','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUFRE2','FREE','SOUTH AFRICA',GetDate(),1)
insert into paperless_puertos values ('AUMEL','MELBOURNE','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUPER','PERTH','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('AUSYD','SYDNEY','AUSTRALIA',GetDate(),1)
insert into paperless_puertos values ('BDCGP','CHITTAGONG','BANGLADESH',GetDate(),1)
insert into paperless_puertos values ('BDMGL','MONGLA','BANGLADESH',GetDate(),1)
insert into paperless_puertos values ('BEANR','ANTWERP','BELGIUM',GetDate(),1)
insert into paperless_puertos values ('BEZEE','ZEEBRUGGE','BELGIUM',GetDate(),1)
insert into paperless_puertos values ('BGVAR','VARNA','BULGARIA',GetDate(),1)
insert into paperless_puertos values ('BHBAH','BAHRAIN','BAHRAIN',GetDate(),1)
insert into paperless_puertos values ('BNMUA','MUARA','BRUNEI',GetDate(),1)
insert into paperless_puertos values ('BRBEL','BELEM','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRFOR','FORTALEZA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIBB','IMBITUBA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIGI','TECON SEPETIBA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIGI2','ITAGUAI','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIGI3','SEPETIBA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIOA','ITAPOA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRIQI','ITAQUI','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRITJ','ITAJAI','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRMAO','MANAUS','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRMCP','SANTANA/MACAPÁ','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRNAT','NATAL','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRNVT','NAVEGANTES','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRPEC','PECEM','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRPNG','PARANAGUA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRPOA','PORTO ALEGRE','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRQNS','CANOAS','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRRIG','RIO GRANDE','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRRIO','RIO DE JANEIRO','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRSFS','MAULDLIN','ESTADOS UNIDOS',GetDate(),1)
insert into paperless_puertos values ('BRSFS2','S.FRANCISCO SUL','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRSSA','SALVADOR','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRSSZ','SANTOS','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRSUA','SUAPE','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRVDC','VILA DO CONDE','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BRVIX','VITORIA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('BSFPO','FREE PORT','BAHAMAS',GetDate(),1)
insert into paperless_puertos values ('CAHAL','HALIFAX','CANADA',GetDate(),1)
insert into paperless_puertos values ('CAMTR','MONTREAL','CANADA',GetDate(),1)
insert into paperless_puertos values ('CATOR','TORONTO','CANADA',GetDate(),1)
insert into paperless_puertos values ('CAVAN','VANCOUVER','CANADA',GetDate(),1)
insert into paperless_puertos values ('CLARI','ARICA','CHILE',GetDate(),1)
insert into paperless_puertos values ('CLSAI','SAN ANTONIO','CHILE',GetDate(),1)
insert into paperless_puertos values ('CLSVE','SAN VICENTE','CHILE',GetDate(),1)
insert into paperless_puertos values ('CLVAP','VALPARAISO','CHILE',GetDate(),1)
insert into paperless_puertos values ('CNBJO','BEIJIAO','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNCAN','GUANGZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNCKG','CHONGQING','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNCSX','CHANGSHA','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNCWN','CHIWAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNCZX','CHANGZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNDCB','DA CHAN BAY','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNDLC','DALIAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNFAN','FANGCHENG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNFOC','FUZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNFOS','FOSHAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNFUG','FUQING','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNGOM','GAOMING','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNHAK','HAIKOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNHUA','HANGPU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNHUA2','HUANGPU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNJGZ','JINGZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNJIA','JIANGYIN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNJMN','JIANGMEN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNLAN','GUANGDONG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNLAN2','LANSHI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNLUU','LELIU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNLYG','LIANYUNGANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNNGB','NINGBO','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNNHK','NANJING','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNNSA','NANSHA','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNNTG','NANTONG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNROQ','RONGQI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSHA','SHANGHAI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSHG','SANSHAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSHG1','SANSHAN, NANHAI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSHK','SHEKOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSNW','SHENWAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSUD','SHUNDE','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSWA','SHANTOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNSZX','SHENZHEN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTAG','TAICANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTAO','QINDAO','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTAO2','HUANGDAO','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTAO3','QINGDAO','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTSN','TIANJIN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNTXG','TIANJINXINGANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNWHI','WUHU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNWUC','WUCHONGKOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNWUH','WUHAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNXGG','XINGANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNXIL','XIAOLAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNXIN','XINHUI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNXMN','XIAMEN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNYTN','YANTIAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNYZH','YANGZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZGA','ZHONGSHAN','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZGA2','ZHONGSHAN WAIMA','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZHE','ZHENJIANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZJG','ZHANGJIAGANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZQG','ZHAOQING','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZUH','ZHUHAI','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZZZ','OUTROS PORTOS','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZZZ2','XIANGZHOU','CHINA',GetDate(),1)
insert into paperless_puertos values ('CNZZZ3','XIANTANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('COBAQ','BARRANQUILA','COLÔMBIA',GetDate(),1)
insert into paperless_puertos values ('COBUN','BUENAVENTURA','COLÔMBIA',GetDate(),1)
insert into paperless_puertos values ('COCTG','CARTAGENA','COLÔMBIA',GetDate(),1)
insert into paperless_puertos values ('COSMR','SANTA MARTA','COLÔMBIA',GetDate(),1)
insert into paperless_puertos values ('CRLIO','PUERTO LIMON','COSTA RICA',GetDate(),1)
insert into paperless_puertos values ('CRMOB','MOIN,LIMON (CR)','COSTA RICA',GetDate(),1)
insert into paperless_puertos values ('CRSJO','SAN JOSE','COSTA RICA',GetDate(),1)
insert into paperless_puertos values ('CUMAR','MARIEL, CUBA','CUBA',GetDate(),1)
insert into paperless_puertos values ('CUSCU','SANTIAGO D CUBA','CUBA',GetDate(),1)
insert into paperless_puertos values ('CVMIN','MINDELO','CABO VERDE',GetDate(),1)
insert into paperless_puertos values ('CYLMS','LIMASSOL','CHIPRE',GetDate(),1)
insert into paperless_puertos values ('DEBRV','BREMERHAVEN','GERMANY',GetDate(),1)
insert into paperless_puertos values ('DEHAM','HAMBURGO','GERMANY',GetDate(),1)
insert into paperless_puertos values ('DKAAR','AMBERES','DINAMARCA',GetDate(),1)
insert into paperless_puertos values ('DKCPH','COPENHAGEN','DINAMARCA',GetDate(),1)
insert into paperless_puertos values ('DKFRC','FREDERICIA','DINAMARCA',GetDate(),1)
insert into paperless_puertos values ('DOCAU','CAUCEDO','REP. DOMINICANA',GetDate(),1)
insert into paperless_puertos values ('ECGYE','GUAYAQUIL','EQUADOR',GetDate(),1)
insert into paperless_puertos values ('EETLL','TALLINN','ESTÔNIA',GetDate(),1)
insert into paperless_puertos values ('EGALY','ALEXANDRIA','EGITO',GetDate(),1)
insert into paperless_puertos values ('EGDAM','DAMIETTA','EGITO',GetDate(),1)
insert into paperless_puertos values ('EGPSD','PORT SAID','EGITO',GetDate(),1)
insert into paperless_puertos values ('ESAGP','MALAGA','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESALG','ALGECIRAS','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESBCN','BARCELONA','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESBIO','BILBAO','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESCAD','CADIZ','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESLPA','LAS PALMAS','CANARY ISLANDS',GetDate(),1)
insert into paperless_puertos values ('ESTAR','TARRAGONA','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESVGO','VIGO','SPAIN',GetDate(),1)
insert into paperless_puertos values ('ESVLC','VALENCIA','SPAIN',GetDate(),1)
insert into paperless_puertos values ('FIHEL','HELSINK','FINLANDIA',GetDate(),1)
insert into paperless_puertos values ('FIRAU','RAUMA','FINLANDIA',GetDate(),1)
insert into paperless_puertos values ('FJSUV','SUVA','FIJI ISLAND',GetDate(),1)
insert into paperless_puertos values ('FRFOS','FOS SUR MER','FRANCE',GetDate(),1)
insert into paperless_puertos values ('FRLEH','LE HAVRE','FRANCE',GetDate(),1)
insert into paperless_puertos values ('FRMRS','MARSEILLE','FRANCE',GetDate(),1)
insert into paperless_puertos values ('FRMTX','M. DE BRETAGNE','FRANCE',GetDate(),1)
insert into paperless_puertos values ('FRMTX2','MONTOIR DE BRET','FRANCE',GetDate(),1)
insert into paperless_puertos values ('FRZZZ','LYON','FRANCE',GetDate(),1)
insert into paperless_puertos values ('GBBEL','BELFAST','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBFXT','FELIXSTOWE','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBGRG','GRANGEMOUTH','UNITED KINGDOM',GetDate(),1)
insert into paperless_puertos values ('GBLGP','LONDON GATEWAY','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBLGP','LONDON','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('GBLIV','LIVERPOOL','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBLON','LONDRES','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBSOU','SOUTHAMPTON-CFS','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBTHP','THAMES PORT','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GBTIL','TILBURY','INGLATERRA',GetDate(),1)
insert into paperless_puertos values ('GPPTP','POINT A PITRE','INDIA',GetDate(),1)
insert into paperless_puertos values ('GRPIR','PIRAEUS','GREECE',GetDate(),1)
insert into paperless_puertos values ('GRSKG','THESSALONIKI','GREECE',GetDate(),1)
insert into paperless_puertos values ('GTGUA','GUATEMALA','GUATEMALA',GetDate(),1)
insert into paperless_puertos values ('GTPBR','PUERTO BARRIOS','GUATEMALA',GetDate(),1)
insert into paperless_puertos values ('GTSTC','S.T.CASTILLA','GUATEMALA',GetDate(),1)
insert into paperless_puertos values ('HKHKG','HONG KONG','HONG KONG',GetDate(),1)
insert into paperless_puertos values ('HNPCR','PUERTO CORTES','HONDURAS',GetDate(),1)
insert into paperless_puertos values ('HNSAP','SAN PEDRO SULA','HONDURAS',GetDate(),1)
insert into paperless_puertos values ('HRRJK','RIJEKA','CROÁCIA',GetDate(),1)
insert into paperless_puertos values ('IDBLW','BELAWAN','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDJKT','TANJUNG PRIOK','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDJKT2','TG. PRIOK','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDJKT3','JAKARTA','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDMAK','MAKASSAR','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDSRG','SEMARANG','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IDSUB','SURABAYA','INDONÉSIA',GetDate(),1)
insert into paperless_puertos values ('IEDUB','DUBLIN','IRLANDA',GetDate(),1)
insert into paperless_puertos values ('ILASH','ASHDOD','ISRAEL',GetDate(),1)
insert into paperless_puertos values ('ILHFA','HAIFA','ISRAEL',GetDate(),1)
insert into paperless_puertos values ('INBLR','BANGALORE','INDIA',GetDate(),1)
insert into paperless_puertos values ('INBOM','MUMBAI','INDIA',GetDate(),1)
insert into paperless_puertos values ('INCCU','CALCUTA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INCCU2','KOLKATA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INCOK','COCHIN','INDIA',GetDate(),1)
insert into paperless_puertos values ('INHAL','HALDIA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INICD','NEW DELHI - IND','INDIA',GetDate(),1)
insert into paperless_puertos values ('INIXV','KANDLA','BRASIL',GetDate(),1)
insert into paperless_puertos values ('INJNT','JNPT','INDIA',GetDate(),1)
insert into paperless_puertos values ('INKNU','KANPUR','INDIA',GetDate(),1)
insert into paperless_puertos values ('INLUH','LUDHIANA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INMAA','CHENNAI','INDIA',GetDate(),1)
insert into paperless_puertos values ('INMAA2','MADRAS','INDIA',GetDate(),1)
insert into paperless_puertos values ('INMDR','MADRAS (CHENAI)','INDIA',GetDate(),1)
insert into paperless_puertos values ('INMUN','MUNDRA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INNIP','GTI','INDIA',GetDate(),1)
insert into paperless_puertos values ('INNIP2','NSICT','INDIA',GetDate(),1)
insert into paperless_puertos values ('INNIP3','NEW DELHI - USA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('INNIP4','NHAVA SHEVA','INDIA',GetDate(),1)
insert into paperless_puertos values ('INNSA','JAWAHARLAL NEHR','INDIA',GetDate(),1)
insert into paperless_puertos values ('INPAV','PIPAVAV','INDIA',GetDate(),1)
insert into paperless_puertos values ('INTUT','TUTICORIN','INDIA',GetDate(),1)
insert into paperless_puertos values ('INVTZ','VISAKHAPATNAM','INDIA',GetDate(),1)
insert into paperless_puertos values ('INZZZ','GTIL','INDIA',GetDate(),1)
insert into paperless_puertos values ('INZZZ2','ICD AHMEDABAD','INDIA',GetDate(),1)
insert into paperless_puertos values ('INZZZ3','HYDERABAD','INDIA',GetDate(),1)
insert into paperless_puertos values ('INZZZ4','JAIPUR','INDIA',GetDate(),1)
insert into paperless_puertos values ('ITAOI','ANCONA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITBRI','BARI','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITCVV','CIVITAVECCHIA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITGIT','GIOIA TAURUS','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITGIT2','GOIA TAURO','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITGOA','GENOVA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITLIV','LEGHORN','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITLIV2','LIVORNO','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITNAP','NAPOLES','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITPMO','PALERMO','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITSAL','SALERNO','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITSPE','LA SPEZIA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITSVN','SAVONA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITVCE','VENEZIA','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('ITVDL','VADO LIGURE','ITÁLIA',GetDate(),1)
insert into paperless_puertos values ('JMKIN','KINGSTON','JAMAICA',GetDate(),1)
insert into paperless_puertos values ('JOAQJ','AQABA','JORDAN',GetDate(),1)
insert into paperless_puertos values ('JPFJS','FUJISAWA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPHKT','HAKATA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPMOJ','MOJI','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPNGO','NAGOYA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPNGS','NAGASAKI','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPOSA','OSAKA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPSMZ','SHIMIZU','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPTOY','TOYAMA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPTYO','TOKYO','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPUKB','KOBE','JAPAN',GetDate(),1)
insert into paperless_puertos values ('JPYOK','YOKOHAMA','JAPAN',GetDate(),1)
insert into paperless_puertos values ('KEMBA','MOMBASA','QUÊNIA',GetDate(),1)
insert into paperless_puertos values ('KHKOS','KOMPONG SOM','CAMBODIA',GetDate(),1)
insert into paperless_puertos values ('KHKOS2','SIHANOUKVILLE','CAMBODIA',GetDate(),1)
insert into paperless_puertos values ('KHPNH','PHNOM PENH','CAMBODIA',GetDate(),1)
insert into paperless_puertos values ('KRICH','INCHON','COREA DO SUL',GetDate(),1)
insert into paperless_puertos values ('KRKAN','KWANGYANG','COREA DO SUL',GetDate(),1)
insert into paperless_puertos values ('KRPUS','BUSAN','COREA DO SUL',GetDate(),1)
insert into paperless_puertos values ('LBBEY','BEIRUT','LEBANON',GetDate(),1)
insert into paperless_puertos values ('LKCMB','COLOMBO','SRI LANKA',GetDate(),1)
insert into paperless_puertos values ('LTKLJ','KLAIPEDA','LITHUANIA',GetDate(),1)
insert into paperless_puertos values ('MAAGA','AGADIR','MARROCOS',GetDate(),1)
insert into paperless_puertos values ('MACAS','CASABLANCA','MOROCCO',GetDate(),1)
insert into paperless_puertos values ('MAPTM','TANGER MED','MARROCOS',GetDate(),1)
insert into paperless_puertos values ('MATNG','PORT TANGIER','MARROCOS',GetDate(),1)
insert into paperless_puertos values ('MATNG','TANGER','MARROCOS',GetDate(),1)
insert into paperless_puertos values ('MMRGN','YANGON','MYANMAR',GetDate(),1)
insert into paperless_puertos values ('MTMAR','MARSAXLOKK','MALTA',GetDate(),1)
insert into paperless_puertos values ('MTMLA','LA VALETTA','MALTA',GetDate(),1)
insert into paperless_puertos values ('MTMLA2','MALTA','MALTA',GetDate(),1)
insert into paperless_puertos values ('MUPLU','PORT LOUIS','ILHAS MAURÍCIO',GetDate(),1)
insert into paperless_puertos values ('MVMLE','MALÉ','ISLAND MALDIVES',GetDate(),1)
insert into paperless_puertos values ('MXATM','ALTAMIRA','MEXICO',GetDate(),1)
insert into paperless_puertos values ('MXESE','ENSENADA','MEXICO',GetDate(),1)
insert into paperless_puertos values ('MXLZC','LAZARO CARDENAS','MEXICO',GetDate(),1)
insert into paperless_puertos values ('MXVER','VERA CRUZ','MEXICO',GetDate(),1)
insert into paperless_puertos values ('MXZLO','MANZANILLO - MX','MEXICO',GetDate(),1)
insert into paperless_puertos values ('MYKUA','KUANTAN','MALAYSIA',GetDate(),1)
insert into paperless_puertos values ('MYPEN','PENANG','MALAYSIA',GetDate(),1)
insert into paperless_puertos values ('MYPEN2','WILLEMSTAD','CURAÇAU',GetDate(),1)
insert into paperless_puertos values ('MYPGU','PASIR GUDANG','MALAYSIA',GetDate(),1)
insert into paperless_puertos values ('MYPKG','PORT KLANG','CHINA',GetDate(),1)
insert into paperless_puertos values ('MYPKG2','PORT KELANG','MALAYSIA',GetDate(),1)
insert into paperless_puertos values ('MYTPP','TANJUNG PELEPAS','MALAYSIA',GetDate(),1)
insert into paperless_puertos values ('MZMNC','NACALA','MOÇAMBIQUE',GetDate(),1)
insert into paperless_puertos values ('NGTIN','TIN CAN ISLAND','NIGÉRIA',GetDate(),1)
insert into paperless_puertos values ('NICIO','CORINTO','NICARÁGUA',GetDate(),1)
insert into paperless_puertos values ('NLRTM','ROTTERDAM','HOLLAND',GetDate(),1)
insert into paperless_puertos values ('NOOSL','OSLO','NORUEGA',GetDate(),1)
insert into paperless_puertos values ('NZAKL','AUCKLAND','NEW ZEALAND',GetDate(),1)
insert into paperless_puertos values ('NZLYT','LYTTELTON','NEW ZEALAND',GetDate(),1)
insert into paperless_puertos values ('NZNPE','NAPIER','NEW ZEALAND',GetDate(),1)
insert into paperless_puertos values ('NZPOE','PORT CHALMERS','NEW ZEALAND',GetDate(),1)
insert into paperless_puertos values ('NZTRG','TAURANGA','NEW ZEALAND',GetDate(),1)
insert into paperless_puertos values ('OMMCT','MUSCAT','OMAN',GetDate(),1)
insert into paperless_puertos values ('OMMCT2','SULTAN QABOOS','UNITED ARABI EMIRATES',GetDate(),1)
insert into paperless_puertos values ('OMSLL','SALALAH','SAUDI ARABIA',GetDate(),1)
insert into paperless_puertos values ('PABLB','BALBOA','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PACTB2','CRISTOBAL','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PAMIT','PORT MANZANILLO','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PAMIT2','MANZANILLO, PAN','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PAONX','COLON','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PAPTY','PANAMA CITY','PANAMÁ, REP. DE PANAMA',GetDate(),1)
insert into paperless_puertos values ('PECLL','CALLAO','PERU',GetDate(),1)
insert into paperless_puertos values ('PHCEB','CEBU','PHILIPPINES',GetDate(),1)
insert into paperless_puertos values ('PHDVO','DAVAO','FILIPINAS',GetDate(),1)
insert into paperless_puertos values ('PHMNL','MANILA','PHILIPPINES',GetDate(),1)
insert into paperless_puertos values ('PKBQM','MUHAMMAD BIN QA','PAKISTAN',GetDate(),1)
insert into paperless_puertos values ('PKBQM2','PORT QASIM','PAKISTAN',GetDate(),1)
insert into paperless_puertos values ('PKKHI','KARACHI','PAKISTAN',GetDate(),1)
insert into paperless_puertos values ('PLGDY','GDYNIA','POLÔNIA',GetDate(),1)
insert into paperless_puertos values ('PLSZZ','SZCZECIN','POLÔNIA',GetDate(),1)
insert into paperless_puertos values ('PTLEI','LEIXOES','PORTUGAL',GetDate(),1)
insert into paperless_puertos values ('PTLIS','LISBOA','PORTUGAL',GetDate(),1)
insert into paperless_puertos values ('PTSIE','SINES','PORTUGAL',GetDate(),1)
insert into paperless_puertos values ('ROCND','CONSTANZA','ROMÊNIA',GetDate(),1)
insert into paperless_puertos values ('SAJED','JEDDAH','SAUDI ARABIA',GetDate(),1)
insert into paperless_puertos values ('SDPZU','PORT SUDAN','SUDÃO',GetDate(),1)
insert into paperless_puertos values ('SEGOT','GOTHENBURG','SUÉCIA',GetDate(),1)
insert into paperless_puertos values ('SEHEL','HELSINGBORG','SUÉCIA',GetDate(),1)
insert into paperless_puertos values ('SGSIN','SINGAPORE','SINGAPORE',GetDate(),1)
insert into paperless_puertos values ('SIKOP','KOPER','ESLOVÊNIA',GetDate(),1)
insert into paperless_puertos values ('SNDKR','DAKAR','SENEGAL',GetDate(),1)
insert into paperless_puertos values ('SRBPM','PARAMARIBO','SURINAME',GetDate(),1)
insert into paperless_puertos values ('SYLTK','LATAKIA','SÍRIA',GetDate(),1)
insert into paperless_puertos values ('THBKK','THAILAND','THAILAND',GetDate(),1)
insert into paperless_puertos values ('THBKK2','BANGKOK','THAILAND',GetDate(),1)
insert into paperless_puertos values ('THLCH','LAEM CHABANG','THAILAND',GetDate(),1)
insert into paperless_puertos values ('TNRDS','RADES','TUNÍSIA',GetDate(),1)
insert into paperless_puertos values ('TRALI','ALIAGA','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRAYT','ANTALYA','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRGEB','GEBZE','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRGEM','GEMLIK','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRHAY','HAYDARPASA','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRIST','ISTAMBUL','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRIZM','IZMIR','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRIZT','IZMIT KORFEZI,','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRKMX','KUMPORT','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRMAR','MARDAS','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRMAR2','MARPORT','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRMER','MERSIN','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TRPAM','AMBARLI','ISTANBUL',GetDate(),1)
insert into paperless_puertos values ('TRZZZ','SOYAK','TURKEY',GetDate(),1)
insert into paperless_puertos values ('TTPOS','PORT OF SPAIN','TRINIDAD E TOBAGO',GetDate(),1)
insert into paperless_puertos values ('TTPTS','POINT LISAS','TRINIDAD E TOBAGO',GetDate(),1)
insert into paperless_puertos values ('TWKEL','KEELUNG','TAIWAN',GetDate(),1)
insert into paperless_puertos values ('TWKHH','KAOHSIUNG','TAIWAN',GetDate(),1)
insert into paperless_puertos values ('TWTPE','TAIPEI','TAIWAN',GetDate(),1)
insert into paperless_puertos values ('TWTXG','TAICHUNG','TAIWAN',GetDate(),1)
insert into paperless_puertos values ('TWTYN','TAOYUAN','TAIWAN',GetDate(),1)
insert into paperless_puertos values ('UAODS','ODESSA','UCRÂNIA',GetDate(),1)
insert into paperless_puertos values ('USBMW','BALTIMORE','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USCHI','CHICAGO','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USCHS','CHARLESTON, SC','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USGLS2','GALVESTON','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USHOU','HOUSTON','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USJAX','JACKSONVILLE','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USLAX','LOS ANGELES','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USLGB','LONG BEACH, CA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USMIA','MIAMI','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USMOB','MOBILE','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USMSY','NEW ORLEANS','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USNNS','NEWPORT NEWS','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USNYC','NEW YORK','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USOAK','OAKLAND, CA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USORF','NORFOLK','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USPDX','PORTLAND','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USPEB','PORT ELIZABETH','SOUTH AFRICA',GetDate(),1)
insert into paperless_puertos values ('USPEF','PORT EVERGLADES','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USPHL','PHILADELPHIA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USPNJ','NEWARK','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USPSM','PORTSMOUTH','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USSAV','SAVANNAH','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USSEA','SEATTLE','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USSLM','NEW JERSEY','ESTADOS UNIDOS',GetDate(),1)
insert into paperless_puertos values ('USTIW','TACOMA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('USTPA','TAMPA','UNITED STATES OF AMERICA',GetDate(),1)
insert into paperless_puertos values ('UYMVD','MONTEVIDEO','URUGUAI',GetDate(),1)
insert into paperless_puertos values ('VELAG','LA GUAIRA','VENEZUELA',GetDate(),1)
insert into paperless_puertos values ('VEPBL','PUERTO CABELLO','VENEZUELA',GetDate(),1)
insert into paperless_puertos values ('VNCLI','CAT LAI (HCM)','VIETNAM',GetDate(),1)
insert into paperless_puertos values ('VNDAD','DA-NANG','VIETNAM',GetDate(),1)
insert into paperless_puertos values ('VNHPH','HAIPHONG','VIETNAM',GetDate(),1)
insert into paperless_puertos values ('VNSGN','HOCHIMINH PORT','VIETNAM',GetDate(),1)
insert into paperless_puertos values ('ZACPT','CAPETOWN','SOUTH AFRICA',GetDate(),1)
insert into paperless_puertos values ('ZADUR','DURBAN','SOUTH AFRICA',GetDate(),1)
insert into paperless_puertos values ('ZAZBA','COEGA','SOUTH AFRICA',GetDate(),1)