ALTER TABLE
    scc.dbo.COTIZACION_INDIRECTA_OPCIONES ADD COTIZACION_SOLICITUD_COTIZACIONES_id bigint


ALTER TABLE
    scc.dbo.COTIZACION_DIRECTA_OPCIONES ADD COTIZACION_INDIRECTA_ESTADOS_id bigint


--falta la columna comentario de COTIZACION_SOLICITUD_COTIZACIONES