USE SCC
GO
-- -----------------------------------------------------
-- Table  mydb . COTIZACION_TIPOS_TRANSBORDOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_TIPOS_TRANSBORDOS') is not null
begin
--ALTER TABLE     COTIZACION_TIPOS_TRANSBORDOS  drop CONSTRAINT DF__COTIZACIO__creat__014935CB    
--ALTER TABLE     COTIZACION_SOLICITUD_COTIZACIONES drop CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_TIPOS_TRANSBORDOS    
 drop table dbo.COTIZACION_TIPOS_TRANSBORDOS
end
GO


CREATE  TABLE  COTIZACION_TIPOS_TRANSBORDOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(45) NOT NULL ,
   createDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
go 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_ESTADOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_ESTADOS') is not null
begin
--ALTER TABLE     COTIZACION_ESTADOS  drop CONSTRAINT DF__COTIZACIO__creat__060DEAE8    
--ALTER TABLE     COTIZACION_SOLICITUD_COTIZACIONES drop CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_ESTADOS    
 drop table dbo.COTIZACION_ESTADOS
end
GO


CREATE  TABLE  COTIZACION_ESTADOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(50) NOT NULL ,
   activo  BIT NULL ,
   createDate  VARCHAR(45) NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_TIPOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_TIPOS') is not null
begin
--ALTER TABLE     COTIZACION_TIPOS  drop CONSTRAINT DF__COTIZACIO__creat__0AD2A005    
--ALTER TABLE     COTIZACION_SOLICITUD_COTIZACIONES drop CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_TIPOS    
 drop table dbo.COTIZACION_TIPOS
end
GO


CREATE  TABLE  COTIZACION_TIPOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(45) NULL ,
   createDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
 
GO

-- -----------------------------------------------------
-- Table  mydb . COTIZACION_SOLICITUD_COTIZACIONES 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_SOLICITUD_COTIZACIONES') is not null
begin
--ALTER TABLE     COTIZACION_SOLICITUD_COTIZACIONES  drop CONSTRAINT DF__COTIZACIO__creat__0F975522    
--ALTER TABLE     COTIZACION_SOLICITUD_COTIZACIONES drop CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_TIPOS    
ALTER TABLE COTIZACION_COMENTARIOS drop CONSTRAINT  COTIZACION_COMENTARIOS_COTIZACION_SOLICITUD_COTIZACIONES
ALTER TABLE COTIZACION_DETALLES drop CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_DETALLES
ALTER TABLE COTIZACION_DIRECTA_OPCIONES drop CONSTRAINT  COTIZACION_DIRECTA_OPCIONES_COTIZACION_SOLICITUD_COTIZACIONES
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES_RELACION drop CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_SOLICITUD_COTIZACIONES
 drop table dbo.COTIZACION_SOLICITUD_COTIZACIONES
end
GO


CREATE  TABLE  COTIZACION_SOLICITUD_COTIZACIONES  (
   id  BIGINT NOT NULL IDENTITY,
   idCliente  BIGINT NULL ,
   idUsuario  BIGINT NULL ,
   nombreCliente  VARCHAR(45) NULL ,
   fechaSolicitud  DATETIME NULL ,--COMMENT '	' ,
   idIncoterms  BIGINT NOT NULL ,--COMMENT 'Aquí poner Referencia a la tabla de incoterms\n' ,
   puertoEmbarque  VARCHAR(100) NULL ,
   POL  VARCHAR(45) NULL ,
   POD  VARCHAR(45) NULL ,
   navieraReferencia  VARCHAR(45) NULL ,
   tarifaReferencia  VARCHAR(45) NULL ,
   mercaderia  VARCHAR(45) NULL ,
   gastosLocales  VARCHAR(45) NULL ,
   proveedorCarga  VARCHAR(45) NULL ,
   credito  VARCHAR(45) NULL ,
   idUsuarioPricing  BIGINT NULL ,
   fechaEstimadaEmbarque  VARCHAR(45)  NULL ,--COMMENT '	' ,
   conAgenciamento  BIT NOT NULL ,
   createDate  DATETIME NOT NULL DEFAULT getdate(),--; ,
   COTIZACION_TIPOS_TRANSBORDOS_id  BIGINT  NULL ,
   COTIZACION_ESTADOS_id  BIGINT NOT NULL ,
   COTIZACION_TIPOS_id  BIGINT NOT NULL ,
  PRIMARY KEY ( id ) )

ALTER TABLE
    COTIZACION_SOLICITUD_COTIZACIONES  ADD CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_TIPOS_TRANSBORDOS FOREIGN KEY (COTIZACION_TIPOS_TRANSBORDOS_ID)
    REFERENCES COTIZACION_TIPOS_TRANSBORDOS (ID)

ALTER TABLE
    COTIZACION_SOLICITUD_COTIZACIONES  ADD CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_TIPOS FOREIGN KEY (COTIZACION_TIPOS_id)
    REFERENCES COTIZACION_TIPOS (ID)

ALTER TABLE
    COTIZACION_SOLICITUD_COTIZACIONES  ADD CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_ESTADOS FOREIGN KEY (COTIZACION_ESTADOS_id)
    REFERENCES COTIZACION_ESTADOS (ID)
    
    

-- -----------------------------------------------------
-- Table  mydb . COTIZACION_ITEMS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_ITEMS') is not null
begin
--ALTER TABLE      COTIZACION_ITEMS drop CONSTRAINT  PK__COTIZACI__3213E83F1273C1CD
 drop table dbo.COTIZACION_ITEMS
end
GO


CREATE  TABLE  COTIZACION_ITEMS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(45) NULL ,
  PRIMARY KEY ( id ) )
GO 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DETALLES 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_DETALLES') is not null
begin
 drop table dbo.COTIZACION_DETALLES 
end
GO


CREATE  TABLE  COTIZACION_DETALLES  (
   id  BIGINT NOT NULL IDENTITY,
   cantidad  DECIMAL(10,6) NULL ,
   COTIZACION_ITEMS_id  BIGINT NOT NULL ,
   COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
   createdate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
GO

ALTER TABLE
    COTIZACION_DETALLES   ADD CONSTRAINT COTIZACION_DETALLES_ITEMS  FOREIGN KEY (COTIZACION_ITEMS_id)
    REFERENCES COTIZACION_ITEMS (ID)

ALTER TABLE
    COTIZACION_DETALLES   ADD CONSTRAINT COTIZACION_SOLICITUD_COTIZACIONES_DETALLES  FOREIGN KEY (COTIZACION_SOLICITUD_COTIZACIONES_id)
    REFERENCES COTIZACION_SOLICITUD_COTIZACIONES (ID)




-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_OPCIONES 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_DIRECTA_OPCIONES') is not null
begin
--ALTER TABLE      COTIZACION_DIRECTA_OPCIONES drop CONSTRAINT  DF__COTIZACIO__creat__1CF15040
ALTER TABLE      COTIZACION_DIRECTA_COMENTARIOS drop CONSTRAINT COTIZACION_DIRECTA_COMENTARIOS_COTIZACION_DIRECTA_OPCIONES
ALTER TABLE      COTIZACION_DIRECTA_ESTADOS drop CONSTRAINT COTIZACION_DIRECTA_ESTADOS_COTIZACION_DIRECTA_OPCIONES
ALTER TABLE      COTIZACION_DIRECTA_OPCIONES_DETALLES drop CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_OPCIONES
 drop table dbo.COTIZACION_DIRECTA_OPCIONES 
end
GO


CREATE  TABLE  COTIZACION_DIRECTA_OPCIONES  (
   id  BIGINT NOT NULL IDENTITY,
   numero  VARCHAR(45) NULL ,
   fechaIngreso  DATETIME NULL ,
   fechaValidezInicio  DATETIME NULL ,
   fechaValidezFin  DATETIME NULL ,
   agente  VARCHAR(45) NULL ,
   naviera  VARCHAR(45) NULL ,
   comentario  VARCHAR(150) NULL ,
   comentarioInterno  VARCHAR(150) NULL ,
   idUsuario  BIGINT NULL ,
   createDate  DATETIME NULL DEFAULT getdate() ,
   COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
   COTIZACION_INDIRECTA_ESTADOS_id  BIGINT NOT NULL ,
  PRIMARY KEY ( id ) )
GO
ALTER TABLE
    COTIZACION_DIRECTA_OPCIONES   ADD CONSTRAINT COTIZACION_DIRECTA_OPCIONES_COTIZACION_SOLICITUD_COTIZACIONES   FOREIGN KEY (COTIZACION_SOLICITUD_COTIZACIONES_id)
    REFERENCES COTIZACION_SOLICITUD_COTIZACIONES (ID)
GO


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_MONEDAS 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_MONEDAS') is not null
begin
ALTER TABLE COTIZACION_DIRECTA_OPCIONES_DETALLES drop CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES_DETALLES  drop CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS
 drop table dbo.COTIZACION_MONEDAS 
end
GO

CREATE  TABLE  COTIZACION_MONEDAS  (
   id  BIGINT NOT NULL IDENTITY,--COMMENT '	' ,
   codigo  VARCHAR(3) NULL ,
   nombre  VARCHAR(45) NULL ,
   activo  BIT NULL ,
   createDate  DATETIME NULL ,
  PRIMARY KEY ( id ) )
 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_ITEMS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_DIRECTA_ITEMS') is not null
begin
ALTER TABLE COTIZACION_DIRECTA_OPCIONES_DETALLES  drop CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_ITEMS
 drop table dbo.COTIZACION_DIRECTA_ITEMS 
end
GO

CREATE  TABLE  COTIZACION_DIRECTA_ITEMS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(45) NULL ,
   descripcion  VARCHAR(100) NULL ,
   activo  BIT NULL ,
  PRIMARY KEY ( id ) )
GO 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_OPCIONES_DETALLES 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_DIRECTA_OPCIONES_DETALLES') is not null
begin
 drop table dbo.COTIZACION_DIRECTA_OPCIONES_DETALLES  
end
GO



CREATE  TABLE  COTIZACION_DIRECTA_OPCIONES_DETALLES  (
   id  BIGINT NOT NULL IDENTITY,
   cantidad  DECIMAL(10,6) NULL ,
   costo  DECIMAL(10,6) NULL ,
   venta  DECIMAL(10,6) NULL ,
   COTIZACION_MONEDAS_id  BIGINT NOT NULL ,
   COTIZACION_DIRECTA_ITEMS_id  BIGINT NOT NULL ,
   COTIZACION_DIRECTA_OPCIONES_id  BIGINT NOT NULL ,
   CreateDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )

ALTER TABLE
    COTIZACION_DIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS   FOREIGN KEY (COTIZACION_MONEDAS_id)
    REFERENCES COTIZACION_MONEDAS (ID)
    
ALTER TABLE
    COTIZACION_DIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_ITEMS   FOREIGN KEY (COTIZACION_DIRECTA_ITEMS_id)
    REFERENCES COTIZACION_DIRECTA_ITEMS (ID)

ALTER TABLE
    COTIZACION_DIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_DIRECTA_OPCIONES_DETALLES_COTIZACION_DIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_DIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_DIRECTA_OPCIONES (ID)            

-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_ESTADOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_DIRECTA_ESTADOS') is not null
begin
 drop table dbo.COTIZACION_DIRECTA_ESTADOS  
end
GO

CREATE  TABLE  COTIZACION_DIRECTA_ESTADOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(50) NOT NULL ,
   activo  BIT NULL ,
   COTIZACION_DIRECTA_OPCIONES_id  BIGINT NOT NULL ,
  PRIMARY KEY ( id ) )
  
 ALTER TABLE
    COTIZACION_DIRECTA_ESTADOS   ADD CONSTRAINT COTIZACION_DIRECTA_ESTADOS_COTIZACION_DIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_DIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_DIRECTA_OPCIONES (ID) 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_ESTADOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_INDIRECTA_ESTADOS') is not null
begin
ALTER TABLE COTIZACION_INDIRECTA_ESTADOS DROP CONSTRAINT DF__COTIZACIO__crete__31EC6D26
ALTER TABLE  COTIZACION_INDIRECTA_OPCIONES DROP CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_COTIZACION_INDIRECTA_ESTADOS
drop table dbo.COTIZACION_INDIRECTA_ESTADOS  
end
GO



CREATE  TABLE  COTIZACION_INDIRECTA_ESTADOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(50) NOT NULL ,
   activo  BIT NULL ,
   cretedate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_OPCIONES 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_INDIRECTA_OPCIONES') is not null
begin
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES DROP CONSTRAINT DF__COTIZACIO__creat__36B12243
ALTER TABLE COTIZACION_INDIRECTA_COMENTARIOS DROP CONSTRAINT COTIZACION_INDIRECTA_COMENTARIOS_COTIZACION_INDIRECTA_OPCIONES
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES_DETALLES DROP CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_INDIRECTA_OPCIONES
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES_RELACION DROP CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES
drop table dbo.COTIZACION_INDIRECTA_OPCIONES  
end
GO



CREATE  TABLE  COTIZACION_INDIRECTA_OPCIONES  (
   id  BIGINT NOT NULL IDENTITY,
   numero  VARCHAR(45) NOT NULL ,
   fechaIngreso  DATETIME NOT NULL ,
   fechaValidezInicio  DATETIME NOT NULL ,
   fechaValidezFin  DATETIME NOT NULL ,
   agente  VARCHAR(45) NULL ,
   comentario  VARCHAR(150) NULL ,
   comentarioInterno  VARCHAR(150) NULL ,
   idUsuario  BIGINT NOT NULL ,
   createDate  DATETIME NOT NULL DEFAULT getdate() ,
   COTIZACION_INDIRECTA_ESTADOS_id  BIGINT NOT NULL ,
   COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
  PRIMARY KEY ( id ) )
GO
ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_COTIZACION_INDIRECTA_ESTADOS    FOREIGN KEY (COTIZACION_INDIRECTA_ESTADOS_id)
    REFERENCES COTIZACION_INDIRECTA_ESTADOS (ID) 
 GO



-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_OPCIONES_copy1 
-- -----------------------------------------------------
--PREGUNTAR A VICTOR

--CREATE  TABLE  COTIZACION_DIRECTA_OPCIONES_copy1  (
--   id  BIGINT NOT NULL IDENTITY,
--   numero  VARCHAR(45) NULL ,
--   fechaIngreso  DATETIME NULL ,
--   fechaValidezInicio  DATETIME NULL ,
--   fechaValidezFin  DATETIME NULL ,
--   agente  VARCHAR(45) NULL ,
--   naviera  VARCHAR(45) NULL ,
--   comentario  VARCHAR(150) NULL ,
--   comentarioInterno  VARCHAR(150) NULL ,
--   createDate  DATETIME NULL DEFAULT getdate() ,
--  PRIMARY KEY ( id ) )
  --UNIQUE INDEX  numero_UNIQUE  ( numero  ASC) )
 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_ITEMS 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_INDIRECTA_ITEMS') is not null
begin
ALTER TABLE  COTIZACION_INDIRECTA_OPCIONES_DETALLES DROP CONSTRAINT  COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_INDIRECTA_ITEMS
drop table dbo.COTIZACION_INDIRECTA_ITEMS  
end
GO


CREATE  TABLE  COTIZACION_INDIRECTA_ITEMS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(45) NULL ,
   descripcion  VARCHAR(100) NULL ,
   activo  BIT NULL ,
  PRIMARY KEY ( id ) )
GO 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_OPCIONES_DETALLES 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_INDIRECTA_OPCIONES_DETALLES') is not null
begin
drop table dbo.COTIZACION_INDIRECTA_OPCIONES_DETALLES  
end
GO

CREATE  TABLE  COTIZACION_INDIRECTA_OPCIONES_DETALLES  (
   id  BIGINT NOT NULL IDENTITY,
   cantidad  DECIMAL(10,6) NULL ,
   costo  DECIMAL(10,6) NULL ,
   venta  DECIMAL(10,6) NULL ,
   COTIZACION_INDIRECTA_OPCIONES_id  BIGINT NOT NULL ,
   COTIZACION_INDIRECTA_ITEMS_id  BIGINT NOT NULL ,
   COTIZACION_MONEDAS_id  BIGINT NOT NULL ,
   CreateDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
 GO 
  ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_INDIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_INDIRECTA_OPCIONES (ID) 
    
ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_INDIRECTA_ITEMS   FOREIGN KEY (COTIZACION_INDIRECTA_ITEMS_id)
    REFERENCES COTIZACION_INDIRECTA_ITEMS (ID) 

ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_DETALLES   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_DETALLES_COTIZACION_MONEDAS   FOREIGN KEY (COTIZACION_MONEDAS_id)
    REFERENCES COTIZACION_MONEDAS (ID) 
GO
-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_ITEMS_copy1 
-- -----------------------------------------------------
--PREGUNTAR A VICTOR
--CREATE  TABLE  COTIZACION_DIRECTA_ITEMS_copy1  (
--   id  BIGINT NOT NULL IDENTITY,
--   nombre  VARCHAR(45) NULL ,
--   descripcion  VARCHAR(100) NULL ,
--   activo  BIT NULL ,
--  PRIMARY KEY ( id ) )
 


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_COMENTARIOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_COMENTARIOS') is not null
begin
drop table dbo.COTIZACION_COMENTARIOS   
end
GO

CREATE  TABLE  COTIZACION_COMENTARIOS  (
   id  BIGINT NOT NULL IDENTITY,
   fecha  DATETIME NULL ,
   EsHistorial  BIT NULL ,
   Comentario  VARCHAR(500) NULL ,
   idUsuario  BIGINT NULL ,
   COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
   CreateDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
  GO
  ALTER TABLE
    COTIZACION_COMENTARIOS   ADD CONSTRAINT COTIZACION_COMENTARIOS_COTIZACION_SOLICITUD_COTIZACIONES   FOREIGN KEY (COTIZACION_SOLICITUD_COTIZACIONES_id)
    REFERENCES COTIZACION_SOLICITUD_COTIZACIONES (ID) 
    GO
-- -----------------------------------------------------
-- Table  mydb . COTIZACION_DIRECTA_COMENTARIOS 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_DIRECTA_COMENTARIOS') is not null
begin
drop table dbo.COTIZACION_DIRECTA_COMENTARIOS
end
GO

CREATE  TABLE  COTIZACION_DIRECTA_COMENTARIOS  (
   id  BIGINT NOT NULL IDENTITY,
   fecha  DATETIME NULL ,
   EsHistorial  BIT NULL ,
   Comentario  VARCHAR(500) NULL ,
   idUsuario  BIGINT NULL ,
   COTIZACION_DIRECTA_OPCIONES_id  BIGINT NOT NULL ,
   CreateDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
  GO
    ALTER TABLE
    COTIZACION_DIRECTA_COMENTARIOS   ADD CONSTRAINT COTIZACION_DIRECTA_COMENTARIOS_COTIZACION_DIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_DIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_DIRECTA_OPCIONES(ID) 
GO
-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_COMENTARIOS 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_INDIRECTA_COMENTARIOS') is not null
begin
drop table dbo.COTIZACION_INDIRECTA_COMENTARIOS
end
GO
CREATE  TABLE  COTIZACION_INDIRECTA_COMENTARIOS  (
   id  BIGINT NOT NULL IDENTITY,
   fecha  DATETIME NULL ,
   EsHistorial  BIT NULL ,
   Comentario  VARCHAR(500) NULL ,
   idUsuario  BIGINT NULL ,
   COTIZACION_INDIRECTA_OPCIONES_id  BIGINT NOT NULL ,
   createDate  DATETIME NULL DEFAULT getdate() ,
  PRIMARY KEY ( id ) )
 GO 
   ALTER TABLE
    COTIZACION_INDIRECTA_COMENTARIOS   ADD CONSTRAINT COTIZACION_INDIRECTA_COMENTARIOS_COTIZACION_INDIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_INDIRECTA_OPCIONES(ID) 
GO   
-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS 
-- -----------------------------------------------------

if object_id('dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS') is not null
begin
ALTER TABLE COTIZACION_INDIRECTA_OPCIONES_RELACION DROP CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS
drop table dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS
end
GO
CREATE  TABLE  COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS  (
   id  BIGINT NOT NULL IDENTITY,
   nombre  VARCHAR(50) NOT NULL ,
   activo  BIT NULL ,
  PRIMARY KEY ( id ) )
 

-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_OPCIONES_RELACION 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION') is not null
begin
drop table dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION
end
GO

CREATE  TABLE  COTIZACION_INDIRECTA_OPCIONES_RELACION  (
   COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
   COTIZACION_INDIRECTA_OPCIONES_id  BIGINT NOT NULL ,
   idUsuario  BIGINT NOT NULL ,
   COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS_id  BIGINT NOT NULL ,
   createDate  DATETIME NOT NULL ,
  PRIMARY KEY ( COTIZACION_SOLICITUD_COTIZACIONES_id ,  COTIZACION_INDIRECTA_OPCIONES_id ) )
  GO
  ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_RELACION   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES   FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_INDIRECTA_OPCIONES(ID) 
  ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_RELACION   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_SOLICITUD_COTIZACIONES   FOREIGN KEY (COTIZACION_SOLICITUD_COTIZACIONES_id)
    REFERENCES COTIZACION_SOLICITUD_COTIZACIONES(ID) 
  ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_RELACION   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS   FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS_id)
    REFERENCES COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS(ID) 
  GO


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS 
-- -----------------------------------------------------
if object_id('dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS') is not null
begin
drop table dbo.COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS
end
GO

CREATE  TABLE  COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS  (
   id  BIGINT NOT NULL IDENTITY,
   fecha  DATETIME NULL ,
   EsHistorial  BIT NULL ,
   Comentario  VARCHAR(500) NULL ,
   idUsuario  BIGINT NULL ,
   COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_SOLICITUD_COTIZACIONES_id  BIGINT NOT NULL ,
   COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES_id  BIGINT NOT NULL ,
  PRIMARY KEY ( id ) )
    GO
    
  --INDEX  fk_COTIZACION_INDIRECTA_COMENTARIOS_copy1_COTIZACION_INDIRE_idx  ( COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_SOLICITUD_COTIZACIONES_id  ASC,  COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES_id  ASC) )
 --DUDA CON ESTE 
--ALTER TABLE
--    COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS_fk1   FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_RELACION_ESTADOS_id)
--    REFERENCES COTIZACION_INDIRECTA_OPCIONES_RELACION(ID) 
  


-- -----------------------------------------------------
-- Table  mydb . COTIZACION_INDIRECTA_ESTADOS_copy1 
-- -----------------------------------------------------
--PREGUNTAR A VICTOR
--CREATE  TABLE  COTIZACION_INDIRECTA_ESTADOS_copy1  (
--   id  BIGINT NOT NULL IDENTITY,
--   nombre  VARCHAR(50) NOT NULL ,
--   activo  BIT NULL ,
--  PRIMARY KEY ( id ) )

GO
 ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS_fk1   
    FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_SOLICITUD_COTIZACIONES_id)
    REFERENCES COTIZACION_SOLICITUD_COTIZACIONES(ID) 
  
ALTER TABLE
    COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS   ADD CONSTRAINT COTIZACION_INDIRECTA_OPCIONES_RELACION_COMENTARIOS_fk2
    FOREIGN KEY (COTIZACION_INDIRECTA_OPCIONES_RELACION_COTIZACION_INDIRECTA_OPCIONES_id)
    REFERENCES COTIZACION_INDIRECTA_OPCIONES(ID) 


GO

