//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCMultimodal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MDICraft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MDICraft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCCMultimodal.MDICraft", typeof(MDICraft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap indexToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("indexToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap manCotDirectas_SmallImage {
            get {
                object obj = ResourceManager.GetObject("manCotDirectas.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MantAgentes_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MantAgentes.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MantComunas_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MantComunas.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MantNavieras_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MantNavieras.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MantPuertos_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MantPuertos.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap menuAdministracion_LargeImage {
            get {
                object obj = ResourceManager.GetObject("menuAdministracion.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuConsultarDueda_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuConsultarDueda.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuConsultarLineaCredito_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuConsultarLineaCredito.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuConsultarVisitas_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuConsultarVisitas.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuCotizaciones_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuCotizaciones.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuDefinirLineaCredito_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuDefinirLineaCredito.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuDefinirTarget_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuDefinirTarget.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuGestionTarger_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuGestionTarger.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuMiCalendario_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuMiCalendario.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuOportunidad_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuOportunidad.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuPaperlessAsignacion_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuPaperlessAsignacion.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuPaperlessAsignar_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuPaperlessAsignar.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuPaperlessGestion_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuPaperlessGestion.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuPaperlessUsuario1_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuPaperlessUsuario1.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuPaperlessUsuario2_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuPaperlessUsuario2.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static bool MenuRegistrarLlamada_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("MenuRegistrarLlamada.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuRegistrarLlamada_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuRegistrarLlamada.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuSalesLead_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuSalesLead.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Point menuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuTarget_LargeImage {
            get {
                object obj = ResourceManager.GetObject("MenuTarget.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuTarget_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuTarget.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MenuTargets_SmallImage {
            get {
                object obj = ResourceManager.GetObject("MenuTargets.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup1_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup1.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup10_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup10.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup2_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup2.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup3_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup3.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup4_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup4.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup5_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup5.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup6_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup6.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup7_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup7.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarGroup8_LargeImage {
            get {
                object obj = ResourceManager.GetObject("navBarGroup8.LargeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem2_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem2.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem3_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem3.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem4_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem4.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem5_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem5.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem6_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem6.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap navBarItem8_SmallImage {
            get {
                object obj = ResourceManager.GetObject("navBarItem8.SmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap newToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("newToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap openToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("openToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap printPreviewToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("printPreviewToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap printToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("printToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap saveToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("saveToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap searchToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("searchToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap statusMensaje_Image {
            get {
                object obj = ResourceManager.GetObject("statusMensaje.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Point statusStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point timer2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Point timer3_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer3.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        public static System.Drawing.Bitmap toolStripDropDownButton1_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButton1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap toolStripSplitButton1_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripSplitButton1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap toolStripSplitButton2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripSplitButton2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Point toolTip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
